version: '3.9'

services:

  laravel-dashboard:
    container_name: laravel_dashboard
    image: alexvelychko/php8
    platform: amd64
    build:
      context: .
      dockerfile: ./.docker/php/prod.dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOCKER_BUILDKIT: 1
      ROOT_PASSWORD: ${ROOT_PASSWORD:-docker}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
    restart: unless-stopped
    tty: true
